#!/bin/bash

podman exec target bash -exc "
  targetcli /backstores/block create name=coreos dev=/dev/disk/by-id/virtio-target
  targetcli iscsi/ create iqn.2023-10.coreos.target.vm:coreos
  targetcli iscsi/iqn.2023-10.coreos.target.vm:coreos/tpg1/luns create /backstores/block/coreos
  targetcli iscsi/iqn.2023-10.coreos.target.vm:coreos/tpg1/ set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1
"

# Will return 0 if the discovery yield a valid portal
iscsiadm -m discovery -p 127.0.0.1 -t st | grep iqn.2023-10.coreos.target.vm:coreos
